### ISSUE TITLE
Is it possible to force an already-built image to be rebuilt?

### ISSUE THREAD

**Issue by selimnairb** [Terrapyn/django_docker_processes#1]
In the run_process task, currently [build image](https://github.com/Terrapyn/django_docker_processes/blob/master/tasks.py#L338) is only called if there are no images by the name *profile.identifier*.  I'd like to be able to force an image to be rebuilt.  I'm not sure how to go about doing this.  When I try something like:

    images = dock.images(name=profile.identifier, quiet=False)
    for image in images:
        dock.remove_image(image['Id'], force=True)

Docker complains that the image doesn't exist.  Obviously I don't understand what I am doing incorrectly.

**Comment by TerraHub** [comment]
This should fix it.  There's now a "rebuild" parameter in the run_process task. If set to true, it will rebuild the image, even if it already exists.
